// Session authentication with two roles:
//   user  - regular passphrase for friends; browse and play only
//   admin - admin passphrase; Admin plus all write operations
// Passwords prefer PBKDF2 hashes stored in the database and editable in Admin,
// falling back to plaintext deployment environment variables for initial setup.
// The cookie carries the role and is signed as a whole.

const COOKIE = "mihonban_session";
const DAY = 86400_000;
const MIN_SESSION_SECRET_LENGTH = 32;
const PBKDF2_ITERS = 210_000; // OWASP 2023 recommendation for PBKDF2-HMAC-SHA256
const MAX_FAILURES = 6;       // Failure limit per IP, tightened from 8
const LOCKOUT_TTL = 900;      // Lockout window in seconds (15 minutes)

const te = (s) => new TextEncoder().encode(s);
const hex = (buf) => [...new Uint8Array(buf)]
  .map((b) => b.toString(16).padStart(2, "0")).join("");

// Constant-time comparison for equal-length hex strings prevents early-return timing leaks.
function timingSafeEqual(a, b) {
  if (typeof a !== "string" || typeof b !== "string" || a.length !== b.length) {
    return false;
  }
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

async function hmac(secret, msg) {
  const key = await crypto.subtle.importKey(
    "raw", te(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
  return hex(await crypto.subtle.sign("HMAC", key, te(msg)));
}

function sessionSecret(env) {
  const secret = env?.SESSION_SECRET;
  return typeof secret === "string" && secret.length >= MIN_SESSION_SECRET_LENGTH
    ? secret : null;
}

// A small random delay slows brute force and masks timing differences for account existence.
const jitterDelay = () =>
  new Promise((r) => setTimeout(r, 120 + Math.floor(Math.random() * 130)));

/* ---------- Password hashing (WebCrypto is available in both Workers and Node) ---------- */

export async function hashPassword(password) {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const key = await crypto.subtle.importKey(
    "raw", te(password), "PBKDF2", false, ["deriveBits"]);
  const bits = await crypto.subtle.deriveBits(
    { name: "PBKDF2", salt, iterations: PBKDF2_ITERS, hash: "SHA-256" },
    key, 256);
  return `pbkdf2$${PBKDF2_ITERS}$${hex(salt)}$${hex(bits)}`;
}

export async function verifyPassword(password, stored) {
  const [scheme, itersText, saltHex, hashHex] = String(stored || "").split("$");
  const iterations = Number(itersText);
  // A corrupted DB value must be treated as a failed login, not as a 500 or
  // an unbounded PBKDF2 workload. Values are generated by hashPassword(), but
  // this guard also protects migrations and manually restored databases.
  if (scheme !== "pbkdf2" || !Number.isSafeInteger(iterations)
      || iterations < 1 || iterations > 1_000_000
      || !/^[0-9a-f]{32}$/i.test(saltHex || "")
      || !/^[0-9a-f]{64}$/i.test(hashHex || "")) {
    return false;
  }
  try {
    const salt = new Uint8Array(saltHex.match(/../g)
      .map((b) => parseInt(b, 16)));
    const key = await crypto.subtle.importKey(
      "raw", te(password), "PBKDF2", false, ["deriveBits"]);
    const bits = await crypto.subtle.deriveBits(
      { name: "PBKDF2", salt, iterations, hash: "SHA-256" },
      key, 256);
    return timingSafeEqual(hex(bits), hashHex.toLowerCase());
  } catch {
    return false;
  }
}

/* ---------- Settings access ---------- */

export async function getSetting(env, k) {
  const row = await env.DB.prepare("SELECT v FROM settings WHERE k = ?")
    .bind(k).first();
  return row ? row.v : null;
}

export async function setSetting(env, k, v) {
  await env.DB.prepare(`INSERT INTO settings (k, v) VALUES (?, ?)
    ON CONFLICT(k) DO UPDATE SET v = excluded.v`).bind(k, String(v)).run();
}

/* ---------- Login check: returns 'admin' | 'user' | null ---------- */

export async function checkPassword(env, password) {
  if (!password) return null;
  const adminHash = await getSetting(env, "admin_pass_hash");
  const admin = adminHash
    ? await verifyPassword(password, adminHash)
    : (!!env.ADMIN_PASSWORD && timingSafeEqual(password, env.ADMIN_PASSWORD));
  if (admin) return "admin";
  const userHash = await getSetting(env, "user_pass_hash");
  const user = userHash
    ? await verifyPassword(password, userHash)
    : (!!env.APP_PASSWORD && timingSafeEqual(password, env.APP_PASSWORD));
  return user ? "user" : null;
}

/* ---------- Session cookie ----------
   The signed payload includes a session epoch (session_epoch). Incrementing it
   after a password change or global sign-out immediately invalidates old cookies.
   The epoch lives in settings and joins the secret in the HMAC. */

async function sessionEpoch(env) {
  return (await getSetting(env, "session_epoch")) || "0";
}

/** Increment the session epoch to invalidate every issued cookie after a password change. */
export function bumpSessionEpochStatement(env) {
  // Let SQLite/D1 perform the increment in one write so simultaneous password
  // changes cannot read the same epoch and accidentally lose an invalidation.
  return env.DB.prepare(`
    INSERT INTO settings (k, v) VALUES ('session_epoch', '1')
    ON CONFLICT(k) DO UPDATE SET v = CAST(COALESCE(settings.v, '0') AS INTEGER) + 1
  `);
}

export async function bumpSessionEpoch(env) {
  await bumpSessionEpochStatement(env).run();
}

export async function sessionCookie(env, role, days = 30) {
  const secret = sessionSecret(env);
  if (!secret) {
    throw new Error(`SESSION_SECRET must contain at least ${MIN_SESSION_SECRET_LENGTH} characters`);
  }
  const exp = Date.now() + days * DAY;
  const epoch = await sessionEpoch(env);
  const sig = await hmac(secret, `${exp}.${role}.${epoch}`);
  // Match project-wide flag semantics: only explicit "1" disables Secure;
  // "0" and "false" do not enable the override.
  const secure = env.DEV_INSECURE_COOKIE === "1" ? "" : " Secure;";
  return `${COOKIE}=${exp}.${role}.${sig}; Path=/; HttpOnly;${secure} ` +
    `SameSite=Lax; Max-Age=${days * 86400}`;
}

/** Return 'admin' | 'user' | null. */
export async function sessionRole(env, req) {
  const secret = sessionSecret(env);
  if (!secret) return null;
  const m = (req.header("Cookie") || "")
    .match(new RegExp(`${COOKIE}=([0-9]+)\\.(admin|user)\\.([0-9a-f]+)`));
  if (!m) return null;
  const [, exp, role, sig] = m;
  if (Number(exp) < Date.now()) return null;
  const epoch = await sessionEpoch(env);
  const expect = await hmac(secret, `${exp}.${role}.${epoch}`);
  return timingSafeEqual(expect, sig) ? role : null; // Constant-time verification
}

const isCompanion = (c) => {
  const key = c.req.header("X-Api-Key");
  const expected = c.env.COMPANION_KEY;
  return typeof key === "string" && typeof expected === "string"
    && expected.length > 0 && timingSafeEqual(key, expected);
};

/** Allow either authenticated role or the companion key. With passwordless guest
 *  access enabled, unauthenticated visitors receive the read-only user role. */
export function requireAuth() {
  return async (c, next) => {
    if (isCompanion(c)) { c.set("role", "companion"); return next(); }
    const role = await sessionRole(c.env, c.req);
    if (role) { c.set("role", role); return next(); }
    if ((await getSetting(c.env, "guest_open")) === "1") {
      c.set("role", "user"); return next();
    }
    return c.json({ error: "unauthorized" }, 401);
  };
}

/** Allow only admins or the companion key for all write operations. */
export function requireAdmin() {
  return async (c, next) => {
    const role = c.get("role");
    if (role === "admin" || role === "companion") return next();
    return c.json({ error: "需要管理员权限" }, 403);
  };
}

/* ---------- Login throttling (failures only; success resets) plus balanced delay ----------
   - Lock an IP for LOCKOUT_TTL seconds after MAX_FAILURES failures.
   - Add 120-250ms of random delay to every attempt, both slowing brute force and
     masking timing differences between matching and nonexistent credentials. */

export async function isThrottled(env, ip) {
  return Number((await env.KV.get(`lt:${ip}`)) || 0) >= MAX_FAILURES;
}

export async function noteLoginFailure(env, ip) {
  const key = `lt:${ip}`;
  const n = Number((await env.KV.get(key)) || 0);
  // Refresh the TTL on every failure: a sustained attack stays locked until it
  // stops for a full LOCKOUT_TTL interval.
  await env.KV.put(key, String(n + 1), { expirationTtl: LOCKOUT_TTL });
}

export async function clearLoginFailures(env, ip) {
  await env.KV.delete(`lt:${ip}`);
}

/** Balanced delay around credential checks to flatten response time and slow brute force. */
export const loginDelay = jitterDelay;
