// 会话认证（双角色）：
//   user  —— 普通口令，给朋友用，只能浏览和播放
//   admin —— 管理员口令，后台 + 一切写操作
// 密码优先读 DB 里的 PBKDF2 哈希（后台可改），没有则回退到部署时的
// 环境变量明文（首次引导）。cookie 携带角色并整体签名。

const COOKIE = "mihonban_session";
const DAY = 86400_000;
const MIN_SESSION_SECRET_LENGTH = 32;
const PBKDF2_ITERS = 210_000; // OWASP 2023 推荐（PBKDF2-HMAC-SHA256）
const MAX_FAILURES = 6;       // 每 IP 失败上限（原 8，收紧）
const LOCKOUT_TTL = 900;      // 锁定窗口秒（15 分钟）

const te = (s) => new TextEncoder().encode(s);
const hex = (buf) => [...new Uint8Array(buf)]
  .map((b) => b.toString(16).padStart(2, "0")).join("");

// 常量时间字符串比较（等长 hex 字符串），杜绝按位提前返回的时序侧信道
function timingSafeEqual(a, b) {
  if (typeof a !== "string" || typeof b !== "string" || a.length !== b.length) {
    return false;
  }
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

async function hmac(secret, msg) {
  const key = await crypto.subtle.importKey(
    "raw", te(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
  return hex(await crypto.subtle.sign("HMAC", key, te(msg)));
}

function sessionSecret(env) {
  const secret = env?.SESSION_SECRET;
  return typeof secret === "string" && secret.length >= MIN_SESSION_SECRET_LENGTH
    ? secret : null;
}

// 小的随机延迟：拖慢暴力破解，同时抹平「用户存在与否」的响应时间差
const jitterDelay = () =>
  new Promise((r) => setTimeout(r, 120 + Math.floor(Math.random() * 130)));

/* ---------- 密码哈希（跨运行时：CF Workers / Node 均有 WebCrypto） ---------- */

export async function hashPassword(password) {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const key = await crypto.subtle.importKey(
    "raw", te(password), "PBKDF2", false, ["deriveBits"]);
  const bits = await crypto.subtle.deriveBits(
    { name: "PBKDF2", salt, iterations: PBKDF2_ITERS, hash: "SHA-256" },
    key, 256);
  return `pbkdf2$${PBKDF2_ITERS}$${hex(salt)}$${hex(bits)}`;
}

export async function verifyPassword(password, stored) {
  const [scheme, itersText, saltHex, hashHex] = String(stored || "").split("$");
  const iterations = Number(itersText);
  // A corrupted DB value must be treated as a failed login, not as a 500 or
  // an unbounded PBKDF2 workload. Values are generated by hashPassword(), but
  // this guard also protects migrations and manually restored databases.
  if (scheme !== "pbkdf2" || !Number.isSafeInteger(iterations)
      || iterations < 1 || iterations > 1_000_000
      || !/^[0-9a-f]{32}$/i.test(saltHex || "")
      || !/^[0-9a-f]{64}$/i.test(hashHex || "")) {
    return false;
  }
  try {
    const salt = new Uint8Array(saltHex.match(/../g)
      .map((b) => parseInt(b, 16)));
    const key = await crypto.subtle.importKey(
      "raw", te(password), "PBKDF2", false, ["deriveBits"]);
    const bits = await crypto.subtle.deriveBits(
      { name: "PBKDF2", salt, iterations, hash: "SHA-256" },
      key, 256);
    return timingSafeEqual(hex(bits), hashHex.toLowerCase());
  } catch {
    return false;
  }
}

/* ---------- 设置存取 ---------- */

export async function getSetting(env, k) {
  const row = await env.DB.prepare("SELECT v FROM settings WHERE k = ?")
    .bind(k).first();
  return row ? row.v : null;
}

export async function setSetting(env, k, v) {
  await env.DB.prepare(`INSERT INTO settings (k, v) VALUES (?, ?)
    ON CONFLICT(k) DO UPDATE SET v = excluded.v`).bind(k, String(v)).run();
}

/* ---------- 登录检查：返回 'admin' | 'user' | null ---------- */

export async function checkPassword(env, password) {
  if (!password) return null;
  const adminHash = await getSetting(env, "admin_pass_hash");
  const admin = adminHash
    ? await verifyPassword(password, adminHash)
    : (!!env.ADMIN_PASSWORD && timingSafeEqual(password, env.ADMIN_PASSWORD));
  if (admin) return "admin";
  const userHash = await getSetting(env, "user_pass_hash");
  const user = userHash
    ? await verifyPassword(password, userHash)
    : (!!env.APP_PASSWORD && timingSafeEqual(password, env.APP_PASSWORD));
  return user ? "user" : null;
}

/* ---------- 会话 cookie ----------
   签名内容含「会话纪元」(session_epoch)：改密/踢出全部登录时递增该值，
   旧 cookie 立即失效。纪元存 settings，随密钥一起进 HMAC。 */

async function sessionEpoch(env) {
  return (await getSetting(env, "session_epoch")) || "0";
}

/** 递增会话纪元 = 让所有已签发 cookie 失效（改密后调用）。 */
export function bumpSessionEpochStatement(env) {
  // Let SQLite/D1 perform the increment in one write so simultaneous password
  // changes cannot read the same epoch and accidentally lose an invalidation.
  return env.DB.prepare(`
    INSERT INTO settings (k, v) VALUES ('session_epoch', '1')
    ON CONFLICT(k) DO UPDATE SET v = CAST(COALESCE(settings.v, '0') AS INTEGER) + 1
  `);
}

export async function bumpSessionEpoch(env) {
  await bumpSessionEpochStatement(env).run();
}

export async function sessionCookie(env, role, days = 30) {
  const secret = sessionSecret(env);
  if (!secret) {
    throw new Error(`SESSION_SECRET must contain at least ${MIN_SESSION_SECRET_LENGTH} characters`);
  }
  const exp = Date.now() + days * DAY;
  const epoch = await sessionEpoch(env);
  const sig = await hmac(secret, `${exp}.${role}.${epoch}`);
  // 与全项目开关约定一致：只有显式 "1" 才关闭 Secure（"0"/"false" 不算开启）
  const secure = env.DEV_INSECURE_COOKIE === "1" ? "" : " Secure;";
  return `${COOKIE}=${exp}.${role}.${sig}; Path=/; HttpOnly;${secure} ` +
    `SameSite=Lax; Max-Age=${days * 86400}`;
}

/** 返回 'admin' | 'user' | null */
export async function sessionRole(env, req) {
  const secret = sessionSecret(env);
  if (!secret) return null;
  const m = (req.header("Cookie") || "")
    .match(new RegExp(`${COOKIE}=([0-9]+)\\.(admin|user)\\.([0-9a-f]+)`));
  if (!m) return null;
  const [, exp, role, sig] = m;
  if (Number(exp) < Date.now()) return null;
  const epoch = await sessionEpoch(env);
  const expect = await hmac(secret, `${exp}.${role}.${epoch}`);
  return timingSafeEqual(expect, sig) ? role : null; // 常量时间校验
}

const isCompanion = (c) => {
  const key = c.req.header("X-Api-Key");
  const expected = c.env.COMPANION_KEY;
  return typeof key === "string" && typeof expected === "string"
    && expected.length > 0 && timingSafeEqual(key, expected);
};

/** 任意已登录角色，或伴侣 key。开启「访客免密」时未登录访客自动获 user（只读）。 */
export function requireAuth() {
  return async (c, next) => {
    if (isCompanion(c)) { c.set("role", "companion"); return next(); }
    const role = await sessionRole(c.env, c.req);
    if (role) { c.set("role", role); return next(); }
    if ((await getSetting(c.env, "guest_open")) === "1") {
      c.set("role", "user"); return next();
    }
    return c.json({ error: "unauthorized" }, 401);
  };
}

/** 仅管理员或伴侣 key（一切写操作）。 */
export function requireAdmin() {
  return async (c, next) => {
    const role = c.get("role");
    if (role === "admin" || role === "companion") return next();
    return c.json({ error: "需要管理员权限" }, 403);
  };
}

/* ---------- 登录限速（只数失败，成功清零）+ 均衡延迟 ----------
   - 每 IP 失败达 MAX_FAILURES 即锁定 LOCKOUT_TTL 秒
   - 每次登录尝试都加 120–250ms 随机延迟：既拖慢暴破，又抹平
     「口令是否命中已存在用户」的时间差 */

export async function isThrottled(env, ip) {
  return Number((await env.KV.get(`lt:${ip}`)) || 0) >= MAX_FAILURES;
}

export async function noteLoginFailure(env, ip) {
  const key = `lt:${ip}`;
  const n = Number((await env.KV.get(key)) || 0);
  // 每次失败刷新 TTL：持续攻击 = 持续锁定，直到停手满 LOCKOUT_TTL 秒
  await env.KV.put(key, String(n + 1), { expirationTtl: LOCKOUT_TTL });
}

export async function clearLoginFailures(env, ip) {
  await env.KV.delete(`lt:${ip}`);
}

/** 登录尝试的均衡延迟（在校验前后调用，抹平响应时间差、拖慢暴破）。 */
export const loginDelay = jitterDelay;
