# -*- coding: utf-8 -*-
"""Generate ``cloud/web/src/zh.js``: a character map from Simplified Chinese
and Japanese shinjitai to Traditional Chinese.

Sources (OpenCC, Apache-2.0):
  STCharacters.txt  Simplified -> Traditional (first Traditional variant)
  JPVariants.txt    Traditional -> Japanese shinjitai (reversed here)
Keep only single-character mappings in the BMP because JavaScript strings index
UTF-16 code units, avoiding surrogate pairs.
Usage: ``python tools/gen-zh.py <STCharacters.txt> <JPVariants.txt>``
"""
import io
import json
import sys
from pathlib import Path

st_path, jp_path = sys.argv[1], sys.argv[2]
out_path = Path(__file__).resolve().parents[1] / "cloud" / "web" / "src" / "zh.js"

def json_str(s):
    return json.dumps(s, ensure_ascii=False)

mapping = {}

def bmp(ch):
    return len(ch) == 1 and ord(ch) <= 0xFFFF

for line in io.open(st_path, encoding="utf-8"):
    line = line.strip()
    if not line or line.startswith("#"):
        continue
    parts = line.split("\t")
    if len(parts) < 2:
        continue
    simp, trads = parts[0], parts[1].split(" ")
    trad = trads[0]
    if bmp(simp) and bmp(trad) and simp != trad:
        mapping[simp] = trad

jp_added = 0
for line in io.open(jp_path, encoding="utf-8"):
    line = line.strip()
    if not line or line.startswith("#"):
        continue
    parts = line.split("\t")
    if len(parts) < 2:
        continue
    trad, jps = parts[0], parts[1].split(" ")
    for jp in jps:
        # Reverse Japanese shinjitai -> Traditional; preserve the higher-priority
        # Simplified -> Traditional table on collisions.
        if bmp(jp) and bmp(trad) and jp != trad and jp not in mapping:
            mapping[jp] = trad
            jp_added += 1

pairs = sorted(mapping.items())
src = "".join(k for k, _ in pairs)
dst = "".join(v for _, v in pairs)

js = u'''// Generated by tools/gen-zh.py from OpenCC data (Apache-2.0); do not edit manually.
// Character map from Simplified Chinese and Japanese shinjitai to Traditional
// Chinese for search normalization, allowing simplified or shinjitai input to
// match the corresponding original names in the library.
const FROM = %s
const TO = %s
let map = null

/** Normalize search by lowercasing and converting Simplified/shinjitai characters to Traditional. */
export function zhNorm(s) {
  if (!map) {
    map = new Map()
    for (let i = 0; i < FROM.length; i++) map.set(FROM[i], TO[i])
  }
  let out = ""
  for (const ch of String(s).toLowerCase()) out += map.get(ch) || ch
  return out
}
''' % (json_str(src), json_str(dst))

io.open(out_path, "w", encoding="utf-8", newline="\n").write(js)
print("pairs:", len(pairs), "(jp added:", jp_added, ") ->", out_path)
